language: R
sudo: false
cache: packages

r:
- 3.2
- 3.3
- oldrel
- release
- devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

addons:
  apt:
    packages:
      libarchive-dev
